var PI = 3.14159265359;
var PI_2 = 2 * 3.14159265359;
var SCR_X = 500; // screen horizonta margin (limits and warping)
var SCR_Y = 500; // screen vertical margin
var Z_POS = 1; // height pos in world (closer to background)
var FLASH_SPEED = 10; // flash speed (per second)
var PLAYER_SCALE = 0.13; // player scale
var PLAYER_SCALE_MINE = 0.22; // player scale with mine
var PLAYER_SPEED = 500; // player speed
var PLAYER_SPEED_MINE = 300; // player speed with mine (fat ass)
var PLAYER_DIE_LEN = 0.2; // player die len (scale + flash)
var PLAYER_MINE_LEN = 0.2; // player pick mine len (scale + flash)
var PLAYER_LASER_LEN = 0.2; // player drop laser len (scale + flash)
var DIST_MINE = 20; // distance from mine to pick
var DIST_MINE_SQ = DIST_MINE * DIST_MINE;
var DIST_LINE = 15; // distance from line to die
var TRANS_TIME = 1.0; // invincible time
var MINE_SPAWN_LEN = 0.3; // mines spawn len (flash, scale and no pick)
var MINE_DIE_LEN = 0.25; // mines die len (flash and disappear)
var MINE_SCALE = 0.13; // mines scale
var TIME_MINES = 7; // time between new mines
var LASER_SCALE = 0.5; // laser scale
var LASER_SPAWN_LEN = 0.6; // lasers spawn len (flash and no damaging)
var LASER_DIE_LEN = 0.25; // lasers die len (flash and no damaging)
var MINE_PROXIMITY_DIST = 10; // minimum distance to any player for any placed mines
var MINE_PROXIMITY_DIST_SQ = MINE_PROXIMITY_DIST * MINE_PROXIMITY_DIST;
var LIGHT_POS_Z = 0.4;
var LIGHT_SCALE = 0.5;
var LIGHT_SCALE_MINE = 1.0;

// colors
var GLOW = 1;
var NOGLOW = 0.5;
var COLORS_RAY = [color(NOGLOW, NOGLOW, GLOW, GLOW), color(GLOW, NOGLOW, NOGLOW, GLOW), color(NOGLOW, GLOW, NOGLOW, GLOW), color(GLOW, NOGLOW, GLOW, GLOW)];
var GLOW = 0.8;
var NOGLOW = 0.3;
var COLORS_PLAYER = [color(NOGLOW, NOGLOW, GLOW, GLOW), color(GLOW, NOGLOW, NOGLOW, GLOW), color(NOGLOW, GLOW, NOGLOW, GLOW), color(GLOW, NOGLOW, GLOW, GLOW)];
var GLOW = 0.8;
var NOGLOW = 0.3;
var COLORS_PLAYER_MINE = [color(NOGLOW, NOGLOW, GLOW, GLOW), color(GLOW, NOGLOW, NOGLOW, GLOW), color(NOGLOW, GLOW, NOGLOW, GLOW), color(GLOW, NOGLOW, GLOW, GLOW)];
var GLOW = 1.0;
var NOGLOW = 1.0;
var COLORS_PLAYER_TRANS = [color(NOGLOW, NOGLOW, GLOW, GLOW), color(GLOW, NOGLOW, NOGLOW, GLOW), color(NOGLOW, GLOW, NOGLOW, GLOW), color(GLOW, NOGLOW, GLOW, GLOW)];
var PLAYER_LIGHTS = [0x2020FF, 0xFF2020, 0x20FF20, 0xFF20FF];
var COLOR_MINE = color(0.1, 0.1, 0.1, 1.0);
var COLOR_FLASH = color(1, 1, 1, 1);
var COLOR_DIE = color(1, 0, 0, 1);
